server:
  port: 8080
spring:
  application:
    name: pay-project
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    #host: 10.1.120.42:6379
    host: 192.168.0.152:7001,192.168.0.152:7002,192.168.0.152:7003,192.168.0.152:7004,192.168.0.152:7005,192.168.0.152:7006
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000ms
    max-redirects: 5
    jedis:
      pool:
        #最大连接数据库连接数,设 0 为没有限制
        max-active: 8
        #最大等待连接中的数量,设 0 为没有限制
        max-idle: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-wait: -1ms
        #最小等待连接中的数量,设 0 为没有限制
        min-idle: 0
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      shutdown-timeout: 100ms








alipay:
  # 支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
  # appid
  appId: 2021000122692484
  # 应用私钥
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDCn4Azza1RZMvjVClty1MWgeS5OGRoD7fzaBjt9bvil+q0mVRgVWg4T8B3nJZHl7ooAEFjS4IdaTrkFbbL6jyF0V67O77X27OMM6uUmz52l1gqqAzSTFUDwWC+VCrBSWag/g/im2EpqgprwD5cgLCYoq1/MI4pyExPZyujYV78WKH7KSHiokhkO+kfH8wm8r89KkWfjXhuzwm7EH3WMfvxKE8XDtK+2qEZ0zwY7cvHSHy4PZgBtT2Ruo//+Zlua6uuMVEi9OZApcp9G3GUakqiuUOhy2wmkcNQ0IGUyWH1OjS7kohDCbRM1w2PZ8ulYdkJ3JGfnNdXrsb4r0b5IRF7AgMBAAECggEBAMHf6/Eu8XmEhIrnuwFxq0pfiP5ty6/SALgLudHKmijGlvrjRydTzSdTYvKEXTviTIIuhvSoMmyj+BNgAiGuLC5N/CVeBeW4KWr/yeuWnqm6aAzOLT+M5J+CEqJm69RyDzdO/3oIuMitaAYgkr7JP6I9Y8GxF91Nd58dsl3l0J5k26ABzFAmPhG9dG95p9xCa/qgyLF/U9L9CHoVuTJl6pXTfghCWeZhtn24OnwIw3dWdJxI87WEECgxaQmYUtlpXsj1TnT1N4AErUPUDDzN8niwh9ImV9sjwgEBwxUIiYO3wQJ2cLeknASBAdPtGn3PAvsTzsD0CumqflKTUaMjSGkCgYEA6DN77qix2Ajf/7HaW5PY2wZflPOTY+aaYIE009IkHmCLYr7Vf0NibQvFBjJ29yhgZr4cP2D6qK8TFKzgoQnoetIPyoWMZglBp+FKerOd2hFlE06R1XUOzpaJGHivENpBqICjSeItPYIPjBBcUZ2EUeff81G+VhhEyWrFJ4fBdmcCgYEA1pIKMBPnl3a4NsAnnP69JQpNTmpbuPIXn0n/Sal17ZyamjXxVLv201TJ16nOG7F9YmlU0BhlI3AqqbaTJLxA/8OqcnJeoRRgoOMfkODwZIrm4qVh+kmtiVU3jnnxtL1nilPaOZcVTNuM7Lo/l7YNz68IHsALp6ZbhGAIfwKeF80CgYEAqZwJt8+TcIkzDbPdGy2IppwmL0gobj2goENg0iTaazH8PpnEm1weRibluNwd1/WvTP0q5wSws4yGtIB+6EKzhRtxm24nmtTCF53R6ITRFdvE5/BpR/FkanS9GZn1zqqOcUXdgHdsslQRhS7iMF+NqsJj7HjWPk8l17Zc4r4gC5sCgYA6IWiHK+1TOIOhuZ9BxjXCAi99bg0ZZuUFb4utDi73x7SO0Mxn02CEUnU4azV+hTBd6AFlOyazWiEEx4THsATABed4iAmhBB9FlyKnInmeE4+HmZyYrTtJeH/LprfX6nRRonP9pDPOFbDxNWgjFtxZBqdhhU/jBIvIqifDGRdxhQKBgGlqNR3ju/aEKpZCFD+UpQPAThn42G85sb3X2bquQmGnoeUSEsVeUNJijDpCKZBi4BStPr+BgjJ0dnjY/zjvfMcv8Pr9WXAvYW1yeAdB+MJYm7erM4Ew7SG0YbTlKzzXrobXmnH7as4fAsnPOF+j+CWNXLgQLyJJpqR6ZmCPHzZU
  # 报文格式
  format: JSON
  # 字符串编码格式
  charset: utf-8
  # 签名方式
  signType: RSA2
  # 支付宝公钥
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlFlvrq8vFdyWKxgJ3Ss33sO/uGQJz0F+gnA9G3FfwKck+CKpKDvYv+V/7GDhv8ec41+uTQeu8k4NN7EOEwjXAHj+h87GEqyeS7E6o2jd8Zt2gcKkP8XJlTOmQ8goy7QafXNaKWNBOR1QND8fXGFNlF+PqV5cDBo8FoNuXXWRtB+us4p/Y7c7FQtfY4G6SMFBYi54wtzcXyFl77+jJ/YAop0qBy0ivjgWKTrrBFiYPv2j43F1f8QL+NUHKjigx7Z2xVnPHBGG6xNZvBVOD8bYtqEZNpYUcWTIdMYDwNiz02AOz1TFVey6fGqUwcbYP8PeY1fl1Zwt31tsV5a9S0Rd6wIDAQAB
  # 支付完成后同步跳转的路径（一般写支付完成后想要跳转的路径）
  returnUrl: http://localhost:9999/#/personal/illegalInfo
  # 异步通知url
  notifyUrl: http://4get9t.natappfree.cc/aliPay/notify

